# SPDX-License-Identifier: GPL-2.0-only
dtbo-y += r0s/r0s_eur_openx_w01_r25.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r21.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r19.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r26.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r23.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r20.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r24.dtbo
dtbo-y += r0s/r0s_eur_openx_w01_r27.dtbo

always-y        := $(dtbo-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtbo